name: docker-image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push memoryGame
        run: |
          docker build -d ${{ secrets.DOCKER_USERNAME }}/MemoryGame ./MemoryGame
          docker push ${{ secrets.DOCKER_USERNAME }}/MemoryGame

      
      - name: Build and push piedrapapeltijereas
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/RockPaperScissors ./RockPaperScissors
          docker push ${{ secrets.DOCKER_USERNAME }}/RockPaperScissors
